name: PHP CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: oopmvc
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_mysql, mbstring

      - name: Wait for MySQL
        run: |
          sudo apt-get install -y mysql-client
          until mysql -h 127.0.0.1 -P 3306 -uroot -proot -e "SELECT 1"; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Import database schema
        run: |
          mysql -h 127.0.0.1 -P 3306 -uroot -proot oopmvc < cobaan.sql

      - name: Install dependencies
        run: |
          if [ -f "composer.json" ]; then
            composer install --no-progress --prefer-dist --optimize-autoloader
          else
            echo "No composer.json found, skipping..."
          fi

      - name: Run tests
        run: |
          if [ -d "tests" ]; then
            ./vendor/bin/phpunit --configuration phpunit.xml
          else
            echo "No tests directory found, skipping..."
          fi
